### ISSUE TITLE
mysql: optimize the `tagMap` mechanism

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go-ext#109]
The `tagMap` mechanism of the `mysql` storage implementation should be optimized. It is being stored as a composite value of a single record in the data table. Instead, the tags should be maintained in a separate 'tags' table. Queries, updates, and deletions involving the `tagMap` should not require SELECT prior to UPDATE/DELETE.  Furthermore, it should be possible to do bulk updates/deletions to the tag map (`see Batch()`).

**Comment by DRK3** [comment]
@llorllale Note this issue here: https://github.com/hyperledger/aries-framework-go-ext/issues/88

**Comment by llorllale** [comment]
OK - closed as this is a duplicate of #88
