### ISSUE TITLE
Update storage interface.

### ISSUE THREAD

**Issue by soluchok** [hyperledger/aries-framework-go-ext#14]
Aries interface was changed. We need to update the storage extensions due to this change. See https://github.com/hyperledger/aries-framework-go/commit/b51ab9afcf161dbbb9ce0d182a938e983bf179c1#diff-5b2df4e72b7663d31d113c48920f911f24be00c599ce90bee6a16253d425e937R63

**Comment by soluchok** [comment]
@DRK3 ^

**Comment by llorllale** [comment]
@soluchok the `Query()` method will be removed shortly

**Comment by DRK3** [comment]
@llorllale You can assign this issue to me. I will take care of this issue once I've finished adding the EDV provider in aries-framework-go.

**Comment by soluchok** [comment]
@DRK3 can we close this issue?

**Comment by DRK3** [comment]
@soluchok Yes. I forgot to close this...

This was completed in #15
