### ISSUE TITLE
Create repo structure

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-framework-go-ext#4]
The following structure is based on known proposed contributions.

Common Actions:
- All contributions must include Apache v2 License headers. This must be enforced by global checks.
- All contributions must be linted. This must be enforced by global checks.
- All contributions must have unit & bdd / integration tests. This must be enforced by global checks.
- Checks should only be run on changed (or new) modules for a particular commit.

Open Questions
- Name of parent folder. Based on a prior [aries presentation](https://docs.google.com/presentation/d/1L5L4QcZOATrn9rj4bEMmlbvij9XWyqgQRoWO-HNiUGw/edit#slide=id.g6f6594a78a_0_58), I am thinking "component".
- Do we have any common code in this repo contained within the top-level module?
- How do we handle codecov?

Structure:

- README
- LICENSE
- .github (workflow definitions)
- go.mod (empty for now)
- Makefile (global checks enforcement)
- component (or ... module | mod | addon | ext) ("plugin" would be confused for go plugins)
  - storage
    - couchdb
      - go.mod
      - go sources (or under pkg directory if needed) - example: store.go, store_test.go
      - Makefile
      - README
      - test
    - mysql | sql (does it make sense to combine several variations of sql)
      - go.mod and other files (see above)
    - postgres (see above)
      - go.mod and other files (see above)
    - mongodb
      - go.mod and other files (see above)
  - vdr
    - indy
      - go.mod and other files (see above)
    - trustbloc
      - go.mod and other files (see above)
  - crypto (future)
  - kms (future)
  - credential | cred (future)
  - protocol (future)
- scripts (common scripts - e.g., checks enforcement).
- test (common test support - if applicable). 
- pkg (TBD: do we have any extension common code - most common code be in the framework repo).
- cmd (TBD: do we have any binaries generated here - initial thought is no).

**Comment by pfeairheller** [comment]
The two extensions that we plan to submit do not share any common code.

Everything else (structure, `component`, etc) looks good to me.
